#!/usr/bin/env python3
"""
CPM Top-K candidate-pool sensitivity sweep + min-var rank-quality diagnostics.

Varies ONLY TOP_K_CANDIDATES (the K feeding the min-variance 50/50 pair
selection). Construction (min-var-pair-50/50, 504d cov) stays fixed.
Outputs research/cpm_topk_sweep_findings.md (written incrementally).
Run: .venv/bin/python research/cpm_topk_sweep.py
"""
from __future__ import annotations
import sys
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import cpm_live as cpm
from cpm_live import (
    load_panel, run_cpm_backtest, perf_metrics,
    faber_sma_xs, best_safe, sig_13612U, min_vol_pair,
    RISKY_UNIVERSE, SAFE_POOL, CANARY_ASSETS, DEFAULT_CASH,
    CANARY_RULE, CORR_LOOKBACK_DAYS,
)
from bull_spy_live import run_bull_spy_backtest
from ndx_sleeve_live import load_ndx_panel, run_ndx_backtest

FINDINGS = ROOT / "research" / "cpm_topk_sweep_findings.md"
WINDOWS = {
    "clean": (pd.Timestamp("2008-05-30"), pd.Timestamp("2026-05-22")),
    "stress": (pd.Timestamp("1999-03-10"), pd.Timestamp("2026-05-22")),
}
K_VALUES = [2, 3, 4, 5, 6]
BLEND_W = {"cpm": 0.60, "bull": 0.20, "ndx": 0.20}

_lines: list[str] = []
def emit(s: str = ""):
    _lines.append(s)
    print(s)
    FINDINGS.write_text("\n".join(_lines) + "\n")


def annualized_turnover(weights_history: list) -> float:
    if not weights_history:
        return float("nan")
    tot = 0.0
    for i in range(1, len(weights_history)):
        prev = weights_history[i - 1]["weights"]
        curr = weights_history[i]["weights"]
        keys = set(prev) | set(curr)
        tot += 0.5 * sum(abs(curr.get(k, 0.0) - prev.get(k, 0.0)) for k in keys)
    af0 = weights_history[0]["apply_from"]
    afn = weights_history[-1]["apply_from"]
    yrs = (afn - af0).days / 365.25
    return tot / yrs if yrs > 0 else float("nan")


def metrics_row(name, daily, cash_daily):
    m = perf_metrics(daily, cash_daily)
    return {"name": name, "sharpe": m["sharpe"], "excess_sharpe": m["excess_sharpe"],
            "cagr": m["cagr"], "vol": m["vol"], "maxdd": m["max_drawdown"],
            "calmar": m["calmar"]}


def cpm_month_diag(close: pd.DataFrame, sig_d, top_k: int):
    monthly = close.loc[:sig_d].resample("ME").last()
    safe = best_safe(monthly, sig_d, SAFE_POOL)
    canary_scores = []
    for c in CANARY_ASSETS:
        if c not in monthly.columns:
            continue
        s = sig_13612U(monthly[c])
        if pd.notna(s):
            canary_scores.append(s)
    if not canary_scores:
        return {"regime": "DEFENSIVE", "pair": None}
    n_pos = sum(1 for s in canary_scores if s > 0)
    if CANARY_RULE == "any_positive" and n_pos == 0:
        return {"regime": "DEFENSIVE", "pair": None}
    faber = faber_sma_xs(monthly)
    avail = [t for t in RISKY_UNIVERSE
             if t in faber.index and pd.notna(faber[t])
             and (sig_d in close.index and pd.notna(close.loc[sig_d].get(t, np.nan)))]
    if not avail:
        return {"regime": "DEFENSIVE", "pair": None}
    daily_rets = close[avail].ffill().pct_change()
    scores = {}
    for t in avail:
        v = daily_rets[t].loc[:sig_d].tail(252).std() * np.sqrt(252)
        if pd.isna(v) or v < 1e-9:
            v = 1.0
        scores[t] = float(faber[t]) / v
    sa = pd.Series(scores)
    ranked = sa.sort_values(ascending=False)
    k = max(2, min(top_k, len(ranked)))
    top = ranked.iloc[:k]
    positive = top[top.index.map(lambda t: faber.get(t, -np.inf) > 0)]
    if len(positive) < 2:
        return {"regime": "RISK_ON", "pair": None,
                "candidates": list(positive.index), "ranked": ranked}
    candidates = list(positive.index)
    pick = min_vol_pair(close.loc[:sig_d, candidates], candidates, CORR_LOOKBACK_DAYS)
    if pick is None:
        return {"regime": "RISK_ON", "pair": None, "candidates": candidates, "ranked": ranked}
    ranks = tuple(candidates.index(a) + 1 for a in pick)
    return {"regime": "RISK_ON", "pair": tuple(pick), "candidates": candidates,
            "ranked": ranked, "ranks": ranks, "n_candidates": len(candidates)}


def signal_dates(close, start, end):
    midx = pd.DataFrame({"x": 1}, index=close.index).groupby(pd.Grouper(freq="ME")).tail(1)
    return midx.index[(midx.index >= start) & (midx.index <= end)].tolist()


def main():
    emit("# CPM Top-K Candidate-Pool Sensitivity + Min-Var Rank-Quality Findings")
    emit()
    emit("Generated by `research/cpm_topk_sweep.py` using `.venv/bin/python`.")
    emit(f"Production K = ceil(8/2) = 4. Construction (min-var 50/50 pair, "
         f"{CORR_LOOKBACK_DAYS}d cov) FIXED; only candidate-pool K varied.")
    emit()
    emit(f"Windows: clean {WINDOWS['clean'][0].date()}..{WINDOWS['clean'][1].date()}, "
         f"stress {WINDOWS['stress'][0].date()}..{WINDOWS['stress'][1].date()}.")
    emit(f"K values: {K_VALUES}. Blend = 60% CPM + 20% BULL-SPY + 20% NDX (raw, "
         f"matches build_dashboard.py).")
    emit()
    emit("Loading panels ...")
    panel = load_panel(start=pd.Timestamp("1993-01-01"))
    ndx_panel = load_ndx_panel()
    cols = sorted(set(RISKY_UNIVERSE + SAFE_POOL + CANARY_ASSETS + [DEFAULT_CASH]) & set(panel.columns))
    close = panel[cols]
    emit(f"Panel: {panel.index[0].date()} -> {panel.index[-1].date()}, {len(panel.columns)} cols.")
    emit()

    orig_k = cpm.TOP_K_CANDIDATES
    results = {}
    for wname, (start, end) in WINDOWS.items():
        shv = panel["SHV"].ffill().pct_change().loc[start:end].fillna(0.0)
        emit(f"[{wname}] computing BULL + NDX sleeves (K-independent) ...")
        bull = run_bull_spy_backtest(panel, start, end)
        ndx_raw, _ = run_ndx_backtest(panel, ndx_panel, start, end)
        for K in K_VALUES:
            cpm.TOP_K_CANDIDATES = K
            cpm_daily, hist = run_cpm_backtest(panel, start, end)
            common = cpm_daily.index.intersection(bull.index).intersection(ndx_raw.index)
            c = cpm_daily.reindex(common).fillna(0.0)
            b = bull.reindex(common).fillna(0.0)
            n = ndx_raw.reindex(common).fillna(0.0)
            blend = BLEND_W["cpm"]*c + BLEND_W["bull"]*b + BLEND_W["ndx"]*n
            shv_c = shv.reindex(common).fillna(0.0)
            results[(wname, K)] = {
                "cpm": metrics_row(f"CPM K={K}", c, shv_c),
                "blend": metrics_row(f"Blend K={K}", blend, shv_c),
                "turnover": annualized_turnover(hist), "hist": hist, "cpm_daily": c,
            }
            r = results[(wname, K)]
            emit(f"[{wname}] K={K}: CPM sharpe={r['cpm']['sharpe']:.3f} "
                 f"cagr={r['cpm']['cagr']*100:.2f}% | blend sharpe={r['blend']['sharpe']:.3f} "
                 f"cagr={r['blend']['cagr']*100:.2f}%")
        cpm.TOP_K_CANDIDATES = orig_k

    emit()
    emit("## Reproduction check (K=4, clean window)")
    c4 = results[("clean", 4)]
    emit(f"CPM standalone:  Sharpe={c4['cpm']['sharpe']:.3f} (target ~1.263), "
         f"CAGR={c4['cpm']['cagr']*100:.2f}% (target ~14.58%)")
    emit(f"60/20/20 blend:  Sharpe={c4['blend']['sharpe']:.3f} (target ~1.503), "
         f"CAGR={c4['blend']['cagr']*100:.2f}% (target ~17.93%)")
    cpm_ok = abs(c4['cpm']['sharpe']-1.263) < 0.03 and abs(c4['cpm']['cagr']-0.1458) < 0.005
    blend_ok = abs(c4['blend']['sharpe']-1.503) < 0.03
    emit(f"Reproduction: CPM {'OK' if cpm_ok else 'MISMATCH'}, blend {'OK' if blend_ok else 'CHECK'}")
    emit()

    for wname in WINDOWS:
        emit(f"## 1. K sweep -- {wname} window")
        emit()
        emit("### CPM standalone")
        emit("| K | Raw Sharpe | Excess Sharpe(SHV) | CAGR | Vol | MaxDD | Calmar | Ann.Turnover |")
        emit("|---|-----------|--------------------|------|-----|-------|--------|--------------|")
        for K in K_VALUES:
            r = results[(wname, K)]["cpm"]; t = results[(wname, K)]["turnover"]
            star = " (PROD)" if K == 4 else ""
            emit(f"| {K}{star} | {r['sharpe']:.3f} | {r['excess_sharpe']:.3f} | "
                 f"{r['cagr']*100:.2f}% | {r['vol']*100:.2f}% | {r['maxdd']*100:.2f}% | "
                 f"{r['calmar']:.3f} | {t*100:.0f}% |")
        emit()
        emit("### Full 60/20/20 blend")
        emit("| K | Raw Sharpe | Excess Sharpe(SHV) | CAGR | Vol | MaxDD | Calmar |")
        emit("|---|-----------|--------------------|------|-----|-------|--------|")
        for K in K_VALUES:
            r = results[(wname, K)]["blend"]
            star = " (PROD)" if K == 4 else ""
            emit(f"| {K}{star} | {r['sharpe']:.3f} | {r['excess_sharpe']:.3f} | "
                 f"{r['cagr']*100:.2f}% | {r['vol']*100:.2f}% | {r['maxdd']*100:.2f}% | "
                 f"{r['calmar']:.3f} |")
        emit()

    start, end = WINDOWS["clean"]
    sdates = signal_dates(close, start, end)
    diags = {K: {sd: cpm_month_diag(close, sd, K) for sd in sdates} for K in K_VALUES}

    emit("## 2. Stability diagnostics vs K=4 baseline (clean window, per month)")
    emit()
    base = diags[4]
    risk_on_months = [sd for sd in sdates if base[sd].get("pair") is not None]
    emit(f"Risk-on months with a selected pair at K=4: {len(risk_on_months)} of {len(sdates)} signal months.")
    emit()
    emit("| K | % months pair IDENTICAL to K=4 | % months >=1 asset overlaps K=4 |")
    emit("|---|-------------------------------|----------------------------------|")
    for K in K_VALUES:
        ident = overlap = n = 0
        for sd in risk_on_months:
            bp = base[sd]["pair"]; kp = diags[K][sd].get("pair"); n += 1
            if kp is None:
                continue
            if set(kp) == set(bp):
                ident += 1
            if set(kp) & set(bp):
                overlap += 1
        emit(f"| {K} | {ident/n*100:.1f}% | {overlap/n*100:.1f}% |")
    emit()

    emit("## 3. Rank-quality diagnostic (PRODUCTION K=4, clean window)")
    emit()
    emit("EAA vol-adj rank (1=best) of the two min-var-selected assets, within the "
         "candidate pool (ordered by vol-adj Faber).")
    emit()
    sel_ranks = []; n_with_rank4 = 0; n_top3 = 0; n_full4 = 0
    rank_member_counts = {1:0,2:0,3:0,4:0,5:0,6:0}; pair_rank_dist = {}
    for sd in risk_on_months:
        d = base[sd]; ranks = d.get("ranks")
        if ranks is None:
            continue
        if d["n_candidates"] == 4:
            n_full4 += 1
        rr = tuple(sorted(ranks)); sel_ranks.append(rr)
        pair_rank_dist[rr] = pair_rank_dist.get(rr, 0) + 1
        for r in ranks:
            rank_member_counts[r] = rank_member_counts.get(r, 0) + 1
        if 4 in ranks:
            n_with_rank4 += 1
        if max(ranks) <= 3:
            n_top3 += 1
    nm = len(sel_ranks)
    mean_rank = float(np.mean([r for rr in sel_ranks for r in rr]))
    emit(f"Risk-on months with a min-var pair: {nm}")
    emit(f"Months where candidate pool == 4 (full K=4 pool): {n_full4} "
         f"({n_full4/nm*100:.1f}% of pairs; rest had <4 positive candidates).")
    emit(f"Mean EAA-rank of selected assets: {mean_rank:.2f} (1=best, lower=more momentum-faithful).")
    emit(f"% months pair drawn ENTIRELY from ranks {{1,2,3}}: {n_top3/nm*100:.1f}%")
    emit(f"% months pair INCLUDES the weakest rank-4 candidate: {n_with_rank4/nm*100:.1f}%")
    emit()
    emit("### Selected-asset rank frequency (counts each pair member)")
    emit("| EAA rank | times selected | % of selected members |")
    emit("|----------|----------------|------------------------|")
    tot_members = sum(rank_member_counts.values())
    for r in sorted(rank_member_counts):
        if rank_member_counts[r] == 0 and r > 4:
            continue
        emit(f"| {r} | {rank_member_counts[r]} | {rank_member_counts[r]/tot_members*100:.1f}% |")
    emit()
    emit("### Pair rank-combination distribution")
    emit("| pair ranks (sorted) | months | % |")
    emit("|---------------------|--------|---|")
    for rr in sorted(pair_rank_dist, key=lambda x: -pair_rank_dist[x]):
        emit(f"| {rr[0]}+{rr[1]} | {pair_rank_dist[rr]} | {pair_rank_dist[rr]/nm*100:.1f}% |")
    emit()

    emit("## 4. Asset-dependence: return contribution by asset (CPM sleeve, K=4)")
    emit()
    daily_ret = close.ffill().pct_change()
    for wname in WINDOWS:
        start_w, end_w = WINDOWS[wname]
        cpm.TOP_K_CANDIDATES = 4
        _, hist = run_cpm_backtest(panel, start_w, end_w)
        cpm.TOP_K_CANDIDATES = orig_k
        contrib = {}; weight_time = {}
        for h in hist:
            mask = (close.index >= h["apply_from"]) & (close.index < h["end_apply"])
            seg = daily_ret.loc[mask]; ndays = int(mask.sum())
            for a, w in h["weights"].items():
                if a in seg.columns:
                    contrib[a] = contrib.get(a, 0.0) + (w * seg[a].fillna(0.0)).sum()
                weight_time[a] = weight_time.get(a, 0.0) + w * ndays
        total = sum(contrib.values()); tot_wt = sum(weight_time.values())
        emit(f"### {wname} window")
        emit("| Asset | Return contribution (sum) | % of CPM total | Avg weight (time) |")
        emit("|-------|---------------------------|----------------|-------------------|")
        for a in sorted(contrib, key=lambda x: -contrib[x]):
            emit(f"| {a} | {contrib[a]*100:.2f}% | {contrib[a]/total*100:.1f}% | "
                 f"{weight_time[a]/tot_wt*100:.1f}% |")
        emit()

    emit("## 5. Verdict (numeric summary)")
    emit()
    clean_cpm_sh = {K: results[("clean", K)]["cpm"]["sharpe"] for K in K_VALUES}
    clean_bl_sh = {K: results[("clean", K)]["blend"]["sharpe"] for K in K_VALUES}
    emit("CPM Sharpe by K (clean): " + ", ".join(f"K{K}={clean_cpm_sh[K]:.3f}" for K in K_VALUES))
    emit("Blend Sharpe by K (clean): " + ", ".join(f"K{K}={clean_bl_sh[K]:.3f}" for K in K_VALUES))
    emit()
    emit("(Narrative verdict appended after numeric review.)")
    print("\nDONE. Findings written to", FINDINGS)


if __name__ == "__main__":
    main()
