from __future__ import annotations
from types import SimpleNamespace

def render_head(ctx: SimpleNamespace) -> str:
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>CPM Strategy Dashboard</title>

<style>
  :root { --bg:#fafafa; --card:#fff; --border:#e8e8e8; --text:#222; --muted:#666; --pos:#1a8a1a; --neg:#cc3333; }
  * { box-sizing: border-box; }
  html, body { overflow-x:hidden; max-width:100vw; }
  body { font-family:-apple-system,BlinkMacSystemFont,'SF Pro',Segoe UI,Roboto,sans-serif;
         background:var(--bg); color:var(--text); margin:0; padding:8px; line-height:1.45; font-size:14px; }
  h1 { font-size:1.4rem; margin:0 0 0.3rem; }
  h2 { font-size:1.1rem; margin:1.2rem 0 0.4rem; padding-bottom:0.3rem; border-bottom:1px solid var(--border); }
  h3 { font-size:1rem; margin:0.8rem 0 0.4rem; }
  h4 { font-size:0.92rem; margin:0.5rem 0 0.3rem; color:var(--muted); }
  p { margin:0.4rem 0; }
  .meta { color:var(--muted); font-size:0.82rem; }
  .card { background:var(--card); border:1px solid var(--border); border-radius:8px;
           padding:8px; margin:8px 0; overflow:hidden; }
  .table-scroll { overflow-x:auto; -webkit-overflow-scrolling:touch; margin:0 -4px; }
  table { border-collapse: collapse; width:100%; font-size:0.85rem; min-width:fit-content; }
  th, td { padding:5px 8px; border-bottom:1px solid var(--border); white-space:nowrap; }
  th { background:#f3f3f3; font-weight:600; text-align:left; position:sticky; top:0; }
  td.pos, .pos { color:var(--pos); }
  td.neg, .neg { color:var(--neg); }
  .perf tr:nth-child(odd), .yearly tr:nth-child(odd) { background:#fcfcfc; }
  .alloc { font-size:0.92rem; width:100%; max-width:none; }
  .alloc td:first-child { font-weight:600; }
  .alloc-grid { display:grid; grid-template-columns: 1fr; gap:10px; }
  ul { margin:0.4rem 0 0.4rem 1.2rem; padding:0; }
  ul li { margin:0.15rem 0; word-wrap:break-word; }
  code { background:#f0f0f0; padding:1px 4px; border-radius:3px; font-size:0.85em;
          word-break:break-all; }
  .perf.alpha-beta td.ab-benchmark { font-size:0.85em; }
  .footnote { font-size:0.78rem; color:var(--muted); margin-top:0.6rem; }
  details summary { cursor:pointer; font-weight:600; padding:5px 0; }
  img.chart { display:block; width:100%; height:auto; max-width:100%; }
  div.chart { width:100%; max-width:100%; overflow-x:auto; }
  div.chart svg { display:block; width:100%; height:auto; max-width:100%; }
  /* Tablet+ */
  @media (min-width: 720px) {
    body { padding:14px; font-size:14px; }
    h1 { font-size:1.5rem; }
    h2 { font-size:1.2rem; }
    .card { padding:14px; margin:10px 0; }
    th, td { padding:6px 10px; }
    .alloc-grid { grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap:14px; }
  }
  /* Desktop */
  @media (min-width: 1024px) {
    body { max-width:1200px; margin:0 auto; padding:20px; }
  }
  /* Print / PDF export */
  @media print {
    body { max-width: 1100px; }
    .card, .chart-card, table {
      break-inside: avoid;
      page-break-inside: avoid;
    }
    .alloc-grid > div {
      break-inside: avoid;
      page-break-inside: avoid;
    }
    table { font-size: 11px; }
    h1, h2, h3, h4 {
      break-after: avoid;
      page-break-after: avoid;
    }
    .warning-banner { break-inside: avoid; }
  }
  .warning-banner {
    color: #888;
    font-size: 0.78rem;
    margin: 4px 0 8px 0;
  }
  .audit-block {
    background: #f0f4f8;
    border: 1px solid #c8d4e0;
    padding: 8px 12px;
    border-radius: 4px;
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 0.78rem;
    color: #333;
    margin: 6px 0;
  }
</style>
</head>
<body>

<p class='warning-banner'>Backtest only, not live-traded. IRA / 401k / Roth only.</p>
""" + f"""
<h1>CPM-NDX-VAL-RPV Strategy Dashboard</h1>
<p class='meta'>{int(ctx.cpm_w*100)}/{int(ctx.ndx_w*100)}/{int(ctx.val_w*100)}/{int(ctx.rpv_w*100)} CPM-NDX-VAL-RPV | monthly rebalance | T+1 OPEN | 10 bps/side | backtest {ctx.window_str} | built {ctx.today}</p>

"""

def render_footer(ctx: SimpleNamespace) -> str:
    return f"""

<p class='footnote' style='margin-top:30px'>Generated by <code>strategy_cpm/build_dashboard.py</code> on {ctx.today}.</p>

</body>
</html>
"""
